packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@better-auth/cli": 1.4.9
  "@better-auth/expo": 1.4.9
  "@eslint/js": ^9.39.2
  "@tailwindcss/postcss": ^4.1.18
  "@tanstack/react-query": ^5.90.20
  "@types/node": ^24.10.2
  better-auth: 1.4.9
  dotenv-cli: ^10.0.0
  eslint: ^9.39.2
  next-themes: ^0.4.6
  prettier: ^3.8.1
  prettier-plugin-tailwindcss: ^0.7.2
  tailwindcss: ^4.1.18
  typescript: ^5.9.3
  typescript-eslint: ^8.54.0
  zod: ^4.3.6

catalogs:
  react19:
    "@types/react": ^19.2.8
    "@types/react-dom": ^19.2.3
    react: 19.2.4
    react-dom: 19.2.4

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

overrides:
  "@types/minimatch": 5.1.2
  lightningcss: 1.30.1

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
