packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tanstack/react-query": ^5.85.5
  "@types/node": ^24.3.1
  eslint: ^9.34.0
  prettier: ^3.6.2
  typescript: ^5.9.2
  zod: ^3.25.67
  "next-themes": ^0.4.6
  "typescript-eslint": ^8.42.0
  "prettier-plugin-tailwindcss": ^0.6.14
  "dotenv-cli": ^8.0.0

catalogs:
  react19:
    "@types/react": ^19.1.12
    "@types/react-dom": ^19.1.9
    react: 19.1.1
    react-dom: 19.1.1

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - bufferutil
  - core-js-pure
  - esbuild
  - keccak
  - msgpackr-extract
  - secp256k1
  - sharp
  - unrs-resolver
  - utf-8-validate
