packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@better-auth/cli": 1.3.34
  "@better-auth/expo": 1.3.34
  "@eslint/js": ^9.39.1
  "@tailwindcss/postcss": ^4.1.17
  "@tanstack/react-query": ^5.90.8
  "@types/node": ^24.10.1
  better-auth: 1.3.34
  dotenv-cli: ^8.0.0
  eslint: ^9.39.1
  next-themes: ^0.4.6
  prettier: ^3.7.4
  prettier-plugin-tailwindcss: ^0.7.2
  tailwindcss: ^4.1.17
  typescript: ^5.9.3
  typescript-eslint: ^8.48.1
  zod: ^4.1.13

catalogs:
  react19:
    "@types/react": ^19.2.7
    "@types/react-dom": ^19.2.3
    react: 19.2.1
    react-dom: 19.2.1

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

overrides:
  "@types/minimatch": 5.1.2
  lightningcss: 1.30.1

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
