packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  "@tailwindcss/postcss": ^4.1.16
  "@tanstack/react-query": ^5.90.5
  "@types/node": ^24.10.0
  dotenv-cli: ^8.0.0
  eslint: ^9.39.1
  "@eslint/js": ^9.39.1
  next-themes: ^0.4.6
  prettier: ^3.6.2
  prettier-plugin-tailwindcss: ^0.6.14
  tailwindcss: ^4.1.16
  typescript: ^5.9.3
  typescript-eslint: ^8.46.4
  zod: ^4.1.12

catalogs:
  react19:
    "@types/react": ^19.2.2
    "@types/react-dom": ^19.2.2
    react: 19.2.0
    react-dom: 19.2.0

linkWorkspacePackages: true

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - esbuild

overrides:
  "@types/minimatch": 5.1.2
  lightningcss: 1.30.1

publicHoistPattern:
  - "@ianvs/prettier-plugin-sort-imports"
  - prettier-plugin-tailwindcss
