packages:
  - apps/*
  - packages/*
  - tooling/*

catalog:
  eslint: ^9.30.0
  prettier: ^3.6.2
  typescript: ^5.8.3
  zod: ^3.25.67
  "@tanstack/react-query": ^5.81.5
  "@types/node": ^24.0.8

catalogs:
  react19:
    react: 19.1.0
    react-dom: 19.1.0
    "@types/react": ^19.1.8
    "@types/react-dom": ^19.1.6

onlyBuiltDependencies:
  - "@tailwindcss/oxide"
  - bufferutil
  - core-js-pure
  - esbuild
  - keccak
  - msgpackr-extract
  - secp256k1
  - sharp
  - unrs-resolver
  - utf-8-validate
